程序在执行过程中，如果出现异常，默认情况锁会释放。

所以在并发处理的过程中，有异常要更加小心，不然可能会发生不一致的情况。

比如，在一个web app处理过程中，多个servlet线程共同访问同一个资源，这时如果异常处理不合适，在第一个线程中抛出异常，其他线程就会进入同步代码区。有可能会访问到异常产生时的数据。

因此要非常小心的处理同步业务逻辑中的异常。

```java
package com.sangyu.test.test23;

/**
 * User: pengyapan
 * Date: 2020/3/26
 * Time: 下午6:55
 */
public class Test1 {
    int count = 0;
    synchronized void m(){
        System.out.println(Thread.currentThread().getName() + " start");
        while (true){
            count++;
            System.out.println(Thread.currentThread().getName() + " count = " + count);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            if (count == 5){
                int i = 1/0; // 此处抛出异常，所将被释放，要想不被释放，可以在这里进行try-catch，然后让循环继续，增加finally，回滚数据
            }
        }
    }

    public static void main(String[] args) {
        Test1 test1 = new Test1();
//        test1.m();
        new Thread(new Runnable() {
            @Override
            public void run() {
                test1.m();
            }
        }).start();

        new Thread(new Runnable() {
            @Override
            public void run() {
                test1.m();
            }
        }).start();
    }
}
```

![](https://upload-images.jianshu.io/upload_images/2765653-ac3c6c3330d88c53.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)